### ISSUE TITLE
Feature request: Support for concatenation of encoder output

### ISSUE THREAD

**Issue by vanrein** [nfcpy/ndeflib#1]
I've used ndeflib in a [simple tool](https://github.com/arpa2/ldap2nfc) but ran into a problem that I hadn't expected; the `message_encoder` cannot be told to refrain from setting `MB` and `ME` flags.  Since I wanted to concatenate individually generated outputs, this means I need to change this after encoding.

One way of doing this generically is to have an `ndef_concat()` function that removes `MB` from all but the first, and `ME` from all but the last.  Another, much simpler way would be extra function options

    def message_encoder (..., first=True, last=True):

that need to be set to `False` to overrule the current / default behaviour of generating `MB` and `ME` on the first and last records.

**Comment by nehpetsde** [comment]
The equivalent of an `ndef_concat` would actually be a `message_decode(..., errors='relax', know_types={})` followed by a `message_encode`. Note that `errors='relax'` is the important part and `known_types={}` will just prevent any decoding of record payloads.

Usually it will be the last step to generate the NDEF byte stream from a list of records assembled for the final message. Your [simple tool](https://github.com/arpa2/ldap2nfc) could probably just do that - successively add vCard and URI records until all NAIs are processed and then generate the NDEF bytes.
